name = "tetsudou"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"
send_metrics = false

kv_namespaces = [
  { binding = "TETSUDOU_REPOS", id = "tetsudou_repos" },
]

[build]
command = "cargo install -q worker-build && worker-build --release"
